### PR TITLE
[WIP]Added xonsh shell in dynamic

### PR DESCRIPTION
**Pull request by sudojarvis**
## Related Issue

Closes: #125 

## Describe the changes you've made

Added xonsh shell in dynamic.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>Screenshot from 2022-03-08 00-06-15use tab for further completion</b> |

### CODE REVIEW

**Comment by sudojarvis** [comment]
@GouravSardana  tests are failing. How can I resolve this?

**Comment by GouravSardana** [comment]
@sudojarvis Wait I'll review it, Will try it locally and give you some suggestions

**Comment by GouravSardana** [comment]
`(temp) gourav@LAPTOP-PHS5P97J:~/ubuntu/dynamic-cli$ xonsh
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    from xonsh.main import main
  File "/home/gourav/ubuntu/dynamic-cli/xonsh/main.py", line 18, in <module>
    from xonsh.codecache import run_script_with_cache
  File "/home/gourav/ubuntu/dynamic-cli/xonsh/codecache.py", line 8, in <module>
    from xonsh.built_ins import XSH
  File "/home/gourav/ubuntu/dynamic-cli/xonsh/built_ins.py", line 24, in <module>
    from xonsh.ast import AST
  File "/home/gourav/ubuntu/dynamic-cli/xonsh/ast.py", line 120, in <module>
    from xonsh.built_ins import XSH
ImportError: cannot import name 'XSH' from partially initialized module 'xonsh.built_ins' (most likely due to a circular import) (/home/gourav/ubuntu/dynamic-cli/xonsh/built_ins.py)`


I pulled your PR locally but i couldn't activate the xonsh. Is there is something which I'm missing ?

**Comment by GouravSardana** [comment]
cc @sudojarvis

**Comment by GouravSardana** [comment]
Just to be sure - When i did "xonsh', It breaks

**Comment by GouravSardana** [comment]
@sudojarvis I tested the changes, suggestion from my end:
- It sometimes break with other configurations make sure all the version are stable
- Do not use others repository code. Try to replicate the feature not the code. 
- I couldn't use dynamic as our common variable to activate the xonsh. I have to use xonsh for this. 
- We couldn't leverage the code which we have in the xonsh folder. Why? -> Because the thing which you showed as history autocomplete is not because of our code but it's just because of the xonsh. For testing -> Do not install dynamic and install just xonsh and type xonsh. You'll get all the functionalities which you showed. We are using xonsh to give our configuration to a single varible - "dynamic"
- Lot's of bugs and security hotspot. So, Please work on that

Do not worry about issue level. I'll make this as level 4 or 5 once you'll understand the scope of this. I hope this make sense. Please let me know if you required anything else from our side.

cc @PradyumnaKrishna @pranavbaburaj

**Comment by sudojarvis** [comment]
yup got it.

**Pull request closed without merging**
