### PR TITLE
Add emojis in Dynamic CLI 

### PR DESCRIPTION
**Pull request by guptaaastha**
## Related Issuse

Dynamic CLI currently puts out plain messages and warnings to the command line, which is not an issue in itself but the user experience can be made more enjoyable and fun with the help of some emojis. This PR addresses this enhancement in user experience.

Closes: #39 

#### Describe the changes you've made

An optional argument `-start` was created. ( `start` would have made it a positional argument in `argparse` which was not desired)
This argument (`-start`) introduces the user to Dynamic CLI in a friendly way with the use of emojis.
Further, various emojis were added in different messages and warnings to make user experience more fun and not bland.
All the emojis were added with `unicode` which is supported by all command line prompts and no dependencies were introduced in `requirements.txt`.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

Since the emojis were added in a lot of places, one screenshot will not do justice to the changes. The following pdf contains all the screenshots associated with the changes.
[Dynamic CLI screenshots.pdf](https://github.com/IndianOpenSourceFoundation/dynamic-cli/files/6222269/Dynamic.CLI.screenshots.pdf)

### CODE REVIEW

**Review by honeybhardwaj — APPROVED** [review]
LGTM !!

**Review by GouravSardana — CHANGES_REQUESTED** [review]
Can you make these changes - 

1. Make 2 args one is -st and the other is --start. So that there should be consistency.
2. Add -st in the ReadME after changing 1.
3. For emoji where do we see the emoji codes because if any of the contributors want to change anything. So that he/she should know. A better way is to add something in the readme that you have taken emojis from this link or we can see emojis code from somewhere!

**Review by anshsrtv — APPROVED** [review]
Great job! 🎉  @guptaaastha

**Comment by guptaaastha** [comment]
> Can you make these changes -
> 
> 1. Make 2 args one is -st and the other is --start. So that there should be consistency.
> 2. Add -st in the ReadME after changing 1.
> 3. For emoji where do we see the emoji codes because if any of the contributors want to change anything. So that he/she should know. A better way is to add something in the readme that you have taken emojis from this link or we can see emojis code from somewhere!

Sure, will make the two changes that you suggested by tomorrow 😄
About the 3rd point, all the emojis are added by using `unicode` which is supported by all major command prompts and no dependencies were added in `requirements.txt`. The `unicodes` can be found at [https://unicode.org/emoji/charts/full-emoji-list.html](url) 😄

**Comment by guptaaastha** [comment]
@GouravSardana I have made all the changes that you've suggested  😄
Please have a look

**Review by GouravSardana — CHANGES_REQUESTED** [review]
Checks are failing due to extra trailing space. You can click on details in the codacy check and you will get the lune number s

**Comment by guptaaastha** [comment]
> Checks are failing due to extra trailing space. You can click on details in the codacy check and you will get the lune number s

Fixed it 😄

**Review by GouravSardana — APPROVED** [review]

**Pull request merged**
