### PR TITLE
Beautified the CLI

### PR DESCRIPTION
**Pull request by pranavbaburaj**
# What did I do
 - Used a module called [lol](https://github.com/pranavbaburaj/lol)(`the module is actually created by me`) to create beautiful input prompts like this:
 
Screenshot (663)

- Enclosed the prompts in a try..except blocks so that we do not get an error(`KeyBoardInterupt`, `EoError`) when the user enters a keyboard shortcut.

 - Used [rich](https://github.com/willmcgugan/rich) to render markdown in the terminal
Screenshot (664)

- Also created a `SearchError` class to throw errors

Please let me know if you find any problems with the code or please merge the branch
And please keep me informed

Hopefully, @pranavbaburaj

### CODE REVIEW

**Review by GouravSardana — CHANGES_REQUESTED** [review]
Can you remove the role of lol module because I don't want it to be dependent because if someday lol has changed then we have to make changes in the code.

**Comment by pranavbaburaj** [comment]
> Can you remove the role of lol module because I don't want it to be dependent because if someday lol has changed then we have to make changes in the code.

Sure, I can do that

**Comment by pranavbaburaj** [comment]
I have added the changes 😄

**Review by GouravSardana — CHANGES_REQUESTED** [review]
Can you make a class of print_makrdown function. So that in the future, we can add more printing markdown

**Review by GouravSardana — CHANGES_REQUESTED** [review]
Specify rich version in the requirements.txt

**Comment by pranavbaburaj** [comment]
Sure 🙂 smile:

**Comment by pranavbaburaj** [comment]
Hey @GouravSardana, I have added all the requested changes

**Comment by pranavbaburaj** [comment]
Hope you will merge the commits

**Pull request merged**
