### PR TITLE
Tags have an optional prompt now

### PR DESCRIPTION
**Pull request by tushar5526**
## Related Issue

Closes: #137 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by pranavbaburaj — COMMENTED** [review]
I'm not sure if that change is necessary. Let's see what @GouravSardana has to say about that.

**Comment by GouravSardana** [comment]
I think this is just a string change to show that tags are optional otherwise user might got confused

**Comment by GouravSardana** [comment]
@pranavbaburaj You can test once locally and I'll also try. Heads up with the approval

**Review by pranavbaburaj — APPROVED** [review]
I tested the changes. I think this can be merged 👍🏾

**Comment by GouravSardana** [comment]
Thanks for your wonderful contributions

**Pull request merged**
