### PR TITLE
Adding support for headers for api calls

### PR DESCRIPTION
**Pull request by utsabc**
## Description

Custom Headers are necessary ingredients for making an authorized request to some end-points, hence support for passing in custom headers can improve the applicability of the service.

In this PR I have added support for adding headers while making GET API calls using the client. The new feature prompts users to input custom headers in their API calls. The user can choose to skip it by pressing enter, otherwise, they can provide a valid Header dictionary which will be parsed and added as headers in the API Call. If any exception occurs while parsing currently printing info [Parse error occured] and continuing the API request.

Inputs:
Screenshot 2021-04-20 at 8 53 56 PM

Webhook Output:
Screenshot 2021-04-20 at 8 54 11 PM

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by GouravSardana** [comment]
LGTM but codacy test is failing because you have a variable called as ex but never used -
`except Exception as ex:`

**Comment by utsabc** [comment]
> LGTM but codacy test is failing because you have a variable called as ex but never used -
> `except Exception as ex:`

@GouravSardana Hey sorry I missed it, fixed the issue.

**Review by anshsrtv — APPROVED** [review]
LGTM! Curious if this can be made a little more interactive and user-friendly. 🤔

**Comment by GouravSardana** [comment]
@anshsrtv Don't you think filling data in the terminal is more painful, if there were multi line header ?
We can open up new issue for that.

**Comment by utsabc** [comment]
> @anshsrtv Don't you think filling data in the terminal is more painful, if there were multi line header ?
> We can open up new issue for that.

I was thinking if we could have some kind of a Text-Area input from the command-line itself, it could also be useful if you want to incorporate POST where you essentially want to parse some Stringified JSON input.

Need to check if there are any library available to do this.

**Comment by GouravSardana** [comment]
@utsabc Please research and create an issue for the same. Meanwhile, I'll merge this change

**Pull request merged**
