### PR TITLE
Made 1 answer visible at a time along with most relevant questions

### PR DESCRIPTION
**Pull request by NamamiShanker**
## Related Issue

- Change the format of results to display them in a more organised manner

Closes: [#33 ]

#### Describe the changes you've made

I made changes to `get_ans` function in `utility.py`. Made some important changes to the function. It now prints the most **Relevant Question** that it found along with the **Most Upvoted Answer** to that question. After that it prints the title and links to other **Relevant Questions** that it found. I have added appropriate comments to show which section of the function performs which step. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
|  |  |

### CODE REVIEW

**Comment by NamamiShanker** [comment]
Hi @anshsrtv ! I don't understand what kind of check am I failing and how can I fix it. Can you please help.

**Comment by GouravSardana** [comment]
Checks are related to greetings. I'll add a new issue for that to make it fix.

**Comment by NamamiShanker** [comment]
Alright! Thanks @GouravSardana

**Comment by pranavbaburaj** [comment]
Hey, I think the pull request is good. But can you find a way to correct the red line. I have opened a pull on this issue - #61. I think you can you can add that feature too, so that I can close my pull 🙁

**Comment by NamamiShanker** [comment]
I can look into that and fix it! But I was thinking will be it better if we completely switch from `rich` to `clint` or `cli`? You guys were discussing about that in #61 . If you think so maybe you can create an issue regarding this. Please let me know what you guys think.

**Comment by pranavbaburaj** [comment]
> I can look into that and fix it! But I was thinking will be it better if we completely switch from `rich` to `clint` or `click`? You guys were discussing that in #61. If you think so maybe you can create an issue regarding this. Please let me know what you guys think.

But, `rich` is the only module in my knowledge, that supports markdown rendering in the terminal . `click` is mostly an arg parser and `clint` doesn't have a markdown renderer. So, It is difficult to remove `rich` from the project

**Comment by NamamiShanker** [comment]
Okay, let me try to fix red lines in my system then.

**Comment by NamamiShanker** [comment]
Hey @pranavbaburaj! I fixed the red line issue. I am attaching two formats of printing results. Which one do you guys prefer?

## Format 1
format1

## Format 2
format2

**Review by GouravSardana — CHANGES_REQUESTED** [review]
1. Start the answers links with 1 
2. if somebody wants to see some other answers as well then there should be option to open any other answers as well like want to open some other answers press answer number.

**Comment by anshsrtv** [comment]
Any updates? @NamamiShanker

**Comment by NamamiShanker** [comment]
@anshsrtv sorry my exams had started. Give me 2 more days.

**Comment by NamamiShanker** [comment]
@anshsrtv Sorry my exams had started. Ill finish this in 2 days.

**Comment by NamamiShanker** [comment]
I have made both the changes. But when I ask to create a pull request, it is creating a new pull request. How do I continue with this pull request?

**Comment by NamamiShanker** [comment]
Hey! I am closing this PR. I'll open a new PR with all the specified changes.

**Pull request closed without merging**
