### PR TITLE
Fixed the red lines

### PR DESCRIPTION
**Pull request by pranavbaburaj**
>  The red lines print in a weird way. from https://github.com/IndianOpenSourceFoundation/dynamic-cli/issues/33#issuecomment-808709528

### CODE REVIEW

**Review by anshsrtv — COMMENTED** [review]
I'm sceptical about using [Clint](https://github.com/kennethreitz-archive/clint) for this issue. We can find another package for the same purpose.

**Comment by pranavbaburaj** [comment]
> I'm sceptical about using [Clint](https://github.com/kennethreitz-archive/clint) for this issue. We can find another package for the same purpose.

Sorry @anshsrtv, can you please recommend any other modules !!

**Comment by anshsrtv** [comment]
> can you please recommend any other modules !!

Can we use [click](https://pypi.org/project/click/) here?

**Comment by GouravSardana** [comment]
@pranavbaburaj provide a screenshot as well to see it :)

**Comment by pranavbaburaj** [comment]
> > can you please recommend any other modules !!
> 
> Can we use [click](https://pypi.org/project/click/) here?

Click does not provide functions for printing colored text I guess. Please correct me if I am wrong

**Comment by pranavbaburaj** [comment]
I think `clint` is the best choice. It also contains several other utilities(like `progress bar etc), which we can use in the future 🙁 . Clint uses the `Colorama module to color the strings

**Review by Siddhant-K-code — APPROVED** [review]
LGTM!

**Review by GouravSardana — APPROVED** [review]
LGTM but as you suggest in #62 If he made these changes as well in the same PR then we will make this PR close.
Let's wait for him

**Comment by pranavbaburaj** [comment]
> LGTM but as you suggest in #62 If he made these changes as well in the same PR then we will make this PR close.
> Let's wait for him

Sure, let's wait

**Comment by pranavbaburaj** [comment]
@GouravSardana, I am closing this pull request. The code is outdated 😑

**Pull request closed without merging**
