### PR TITLE
fix: Fix module issue mentioned in #178

### PR DESCRIPTION
**Pull request by pranavbaburaj**
## Related Issue
#178 

Closes: #178

### CODE REVIEW

**Comment by pranavbaburaj** [comment]
Oof. I accidentally included the build files. Ill create a new pull request with the changes

**Comment by GouravSardana** [comment]
@pranavbaburaj click on files which you edited and see there were few warnings related to import sequencing and few others

**Comment by pranavbaburaj** [comment]
Ill fix it in a bit

**Comment by pranavbaburaj** [comment]
@GouravSardana, when i ran through the errors. most of the errors are wrong. The stuff they say doesn't exist actually does exist

**Comment by GouravSardana** [comment]
LGTM, I tested in local

**Pull request merged**
