### PR TITLE
GIFs added

### PR DESCRIPTION
**Pull request by shreya024**
## Related Issue
New GIFs Added to README

Closes: #158 

## Describe the changes you've made
Added 4 GIFs for 
- APIs testing -> GET, POST
- Dynamic Search
- saving to the playbook
- Retrieving from Playbook

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by GouravSardana** [comment]
@shreya024 LGTM. Can you please add those GIFs in a folder in this repository?

Make a folder named static/img and store all the GIFs in it.

**Review by pranavbaburaj — APPROVED** [review]

**Comment by shreya024** [comment]
@GouravSardana Thank you so much for merging.Kindly add the GSSoC label

**Comment by GouravSardana** [comment]
@shreya024 done

**Comment by shreya024** [comment]
> @shreya024 done

Thank you so much.Could you kindly add a Level- as well otherwise my scores are not getting added

**Comment by GouravSardana** [comment]
@shreya024 added

**Pull request merged**
