### PR TITLE
Add Testing section in README.md

### PR DESCRIPTION
**Pull request by adii21-Ux**
## Related Issue

Closes: #173 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by GouravSardana** [comment]
Is this contains both of the changes(tests and readme edit)? If yes, please update the title of the PR. It seems you only updated readme from the given title @adii21-Ux

**Comment by adii21-Ux** [comment]
@GouravSardana fixed commits

**Comment by GouravSardana** [comment]
cc @pranavbaburaj @PradyumnaKrishna @peb-peb

**Review by pranavbaburaj — APPROVED** [review]
Looks good

**Review by PradyumnaKrishna — APPROVED** [review]
LGTM

**Comment by adii21-Ux** [comment]
@GouravSardana can you please add issue about DELETE and PUT

**Pull request merged**
