### PR TITLE
Implement GET in dynamic to get the response from an API

### PR DESCRIPTION
**Pull request by yasht01**
## Related Issue

Closes: #75

## Describe the changes you've made

Created a new file `api_test.py` for keeping all the API testing code. Created a custom class `Api_Testing` having member functions `get_request()` and `check_endpoint()` for making GET requests. `get_request()` makes the API call and saves the data in `response_data.json` as well print the response status code for further information about the call, if it fails. Also, it provides info about the error encountered during the API call. `check_endpoint()` checks whether the `input_url` has an endpoint or not. If not, the CLI will ask for the endpoint and then make the request.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

If the URL has no endpoint:

image

If the URL has an endpoint:

image

Response data:

image

### CODE REVIEW

**Comment by yasht01** [comment]
Hey, I tried looking into the failing check but it has no explanation about what is wrong with the code.

**Comment by GouravSardana** [comment]
@anshsrtv @pranavbaburaj can you check why codacy scanner is failing ? 
Please let me know if you need any access

**Comment by GouravSardana** [comment]
@yasht01 There is one code smell ny the sonar. Please solve that

**Comment by GouravSardana** [comment]
I rerun the test. It works fine now. Solve the code smell one

**Review by anshsrtv — CHANGES_REQUESTED** [review]
Great job @yasht01 It was indeed a challenging issue 🚀 👏 Some suggestions, I would like to point out:

- Since you are asking for the URL first, let that be the complete URL and not just the domain name/IP address. 
- If the user does not provide the schema (`HTTP` or `HTTPS`) in the URL, choose a default and proceed. 
- It's always a good idea to use the `self` keyword inside a method, to refer to the class instance.
- You are printing this message too early. The JSON file was not created in the below case. 
```
Response data stored in response_data.json
```
image

**Comment by anshsrtv** [comment]
@GouravSardana Is it required to store the response in a file? If it is, we will have to update the `.gitignore` as well.

**Comment by GouravSardana** [comment]
No @anshsrtv , we can't store it in a file. Motto is to display the json with proper indentation with colors in the terminal itself and we can give a option to the user if he want to save ut in a file or not. If he say 'y' then we can save it else not

**Comment by yasht01** [comment]
@anshsrtv
> Since you are asking for the URL first, let that be the complete URL and not just the domain name/IP address.

Can I remove the `check_endpoint()` function as the user will give the complete URL?

**Comment by yasht01** [comment]
Hey, for fixing the code smells, the tool says to rename the `self` to `cls`.

image

But, renaming it to `cls` produces an error `NameError: name 'self' is not defined`. How can I fix this code smell?

**Comment by yasht01** [comment]
image

I have created option for user to save the data and I have added output formatting for reponse data in the terminal

**Comment by anshsrtv** [comment]
> Hey, for fixing the code smells, the tool says to rename the `self` to `cls`.
> 
> image
> 
> But, renaming it to `cls` produces an error `NameError: name 'self' is not defined`.
> Also, if I remove the `@classmethod`, then I get this error `TypeError: __check_endpoint() missing 1 required positional argument: 'request_url'`
> How can I fix this code smell?

Change back to `cls` and replace `self` with `cls` in lines 10,16,19 & 56 of `api_test.py`.

**Comment by GouravSardana** [comment]
Does it care about the upper case and lower case letters or Y and N ?

**Comment by yasht01** [comment]
No, I have added code to accept 'Y' or 'y'

**Comment by GouravSardana** [comment]
LGTM !

@pranavbaburaj @anshsrtv Do you want to suggest anything from your side ?

**Review by anshsrtv — APPROVED** [review]

**Comment by anshsrtv** [comment]
Should we add `access_token.json`, `response_data.json` to `.gitignore`?

**Comment by yasht01** [comment]
Yeah, `access_token.json` contains tokens attached to a user and should be kept private. Can I modify the `.gitignore`?

**Comment by GouravSardana** [comment]
Yes, Go ahead

**Pull request merged**
