### PR TITLE
Add feature to setup custom API key

### PR DESCRIPTION
**Pull request by yasht01**
## Related Issue

Closes: #48 

## Describe the changes you've made 
Added a function `setCustomKey()` in `utility.py` file for performing authentication and saving the access token data to `access_token.json`. Added code in `main.py` file to show a command-line argument(`-c / --custom`) for setting custom API key. Also, added an `elif` statement in `search.py` to make the `setCustomKey()` function call.

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### The user then pastes the URL after authentication back into the terminal.

image

### The access token data is stored in `access_token.json` file.

image

### CODE REVIEW

**Comment by GouravSardana** [comment]
Our cli is using the public API end points. If user set his own custom key then still our cli search with public end point or different end points ?

**Comment by yasht01** [comment]
The custom API key can be used to access some data which requires authentication. Like we can add an [answer](https://api.stackexchange.com/docs/create-answer) or [read inbox](https://api.stackexchange.com/docs/me-inbox) of a particular user. Some services can be accessed using a public URL while others need authentication and an access token.

**Review by GouravSardana — APPROVED** [review]
LGTM

**Comment by GouravSardana** [comment]
Alright. So, I think we don't have these endpoints right now i.e answer a question or read inboxes. We will create it later on. For now, It's looking good, and thanks for contributing.

**Review by pranavbaburaj — APPROVED** [review]
It looks good 🙂

**Review by anshsrtv — APPROVED** [review]
Great job working on the issue 🚀 
```
Paste URL after authenticating here: 
```
Can we automate this part? I mean it's a hassle to copy-paste the URL in CLI. Is there a way to redirect to the CLI after successful authentication?

**Comment by yasht01** [comment]
@anshsrtv I was also searching about the same thing. I will report back if I find a workaround 🤞

**Comment by yasht01** [comment]
@anshsrtv I looked into making this process automatic using selenium library. They have mentioned that we would have to download a [web driver](https://selenium-python.readthedocs.io/installation.html#drivers) of any browser for creating a script for this purpose. Will this be feasible for a user to download a web driver and then use the CLI?

**Comment by anshsrtv** [comment]
> Will this be feasible for a user to download a web driver and then use the CLI?

I don't think so. @GouravSardana @pranavbaburaj What do you guys think, can we opt for it?

And @yasht01 the `search.py` has some merge conflicts, which is why the checks are failing. Please check that.

**Comment by GouravSardana** [comment]
@anshsrtv I don't think so. Yash, you can add webdriver in the requirements itself. So that it will automatically get installed while installing dynamic cli. Then it would be easy

**Comment by GouravSardana** [comment]
Checks are failing. Please fix thise

**Comment by yasht01** [comment]
@anshsrtv I added a small selenium script to open a browser and gave a timeout of 30 seconds for the user to login. One requirement for the user would be to have one of these browsers: Chrome, Firefox or Edge

**Pull request merged**
