### PR TITLE
Create navigation enabled question panel

### PR DESCRIPTION
**Pull request by NamamiShanker**
## Related Issue
 - No navigation with arrow keys in StackOverflow question panel
 - Can't exit panel with 'Esc' or 'Q' key
 - Value Error in input

Closes: #87 #41 

## Describe the changes you've made
Created a different class for displaying and navigating through the StackOverflow question panel. Users can now navigate through the questions with arrow keys, exit with the 'q' key or 'Esc' key, press 'Enter' to open the question in a browser. The question panel also has Vim-style searching capability with the '/' key. The CLI is very smooth now, although the downside is it takes a bit more time to search as it now downloads answers to all the questions beforehand.

There is a small issue - Sometimes, long markdown texts run off the preview panel. That may cause some problems when the terminal is not used on the full screen. I need some help in fixing that. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **before** | <b>after</b> |

### CODE REVIEW

**Comment by NamamiShanker** [comment]
The questions panel is really cool now. @GouravSardana @anshsrtv your views?

**Comment by NamamiShanker** [comment]
I'll fix codacy issues

**Comment by NamamiShanker** [comment]
I'll fix codacy issues

**Comment by NamamiShanker** [comment]
@GouravSardana @anshsrtv, please review the PR

**Comment by GouravSardana** [comment]
Please check one code smell by sonar cloud

**Review by anshsrtv — CHANGES_REQUESTED** [review]
Wonderful work 🚀 Just check why did I get this error, searching for `git fetch` with `git` as the tag.
```
  File "~/dynamic-cli/src/arguments/utility.py", line 90, in return_formatted_ans
    body_markdown = self.answer_data[int(ques_id)]
ValueError: invalid literal for int() with base 10: ' What is the difference?'
```

**Comment by NamamiShanker** [comment]
@GouravSardana @anshsrtv I have fixed both the issue

**Comment by GouravSardana** [comment]
One issue from my end - If you see the previous screenshot, the code is coming in the black screen which looks more attractive in terms of user experience. Can you please make that change?

**Comment by GouravSardana** [comment]
Rest everything LGTM 🥇

**Comment by NamamiShanker** [comment]
I will try to do it. The thing is I have used the `simple-term-menu` library to display the questions and preview panel. It doesn't work with `rich` library. I have used `pygments` lexers and formatters to style the output. I'll check if there is some way to implement background color in the terminal with it.

**Comment by GouravSardana** [comment]
But we can use rich only for displaying the message or is it conflicting with your module?

**Comment by NamamiShanker** [comment]
We can use rich for displaying text. The text gets rendered in the preview panel a but weirdly. I'll send you some screenshots. Some code needs to filter the render characters to simple ones. I have managed to make a simple one with work okay.

**Comment by NamamiShanker** [comment]
How does this look? @GouravSardana 

new_background

**Comment by NamamiShanker** [comment]
Also, does this PR close issue #41 ?

**Comment by GouravSardana** [comment]
This looks good and I'll review it and close the PR

**Comment by GouravSardana** [comment]
Did you commit these changes to the PR ?

**Comment by GouravSardana** [comment]
Yup. This Will close #41 as well

**Comment by NamamiShanker** [comment]
@GouravSardana I have committed the changes to PR. Please merge and close it.

**Comment by GouravSardana** [comment]
LGTM. Closing it. Thank you for your contribution :)

**Review by pranavbaburaj — COMMENTED** [review]
Thanks a lot

**Comment by NamamiShanker** [comment]
Always happy to contribute! I really like the idea of this project and I'll keep contributing.

**Comment by NamamiShanker** [comment]
Hey! @GouravSardana can I change the gif in README?

**Comment by NamamiShanker** [comment]
Hey @GouravSardana you forgot to give GSSOC and Label to my PRs. This one and #82. Can you please do that now?

**Pull request merged**
