### PR TITLE
Added Codacy Analysis CLI Action

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Related Issue

Closes: #19 

## Describe the changes you've made

Added Codacy Analysis CLI GitHub Action which analyses code changes ( it Analyzes each commit or pull request )

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by honeybhardwaj — CHANGES_REQUESTED** [review]
Hi , This is the default case for codacy cli which just fails the check if there is a presence of issue and show details on issue other than this you could go with the codacy cli with integration of github codescanning . it will let us see the problem with the code in security tab of github. refer: [link](https://github.com/codacy/codacy-analysis-cli-action#integration-with-github-code-scanning) and make the necessary changes

**Comment by Siddhant-K-code** [comment]
> Hi , This is the default case for codacy cli which just fails the check if there is a presence of issue and show details on issue other than this you could go with the codacy cli with integration of github codescanning . it will let us see the problem with the code in security tab of github. refer: [link](https://github.com/codacy/codacy-analysis-cli-action#integration-with-github-code-scanning) and make the necessary changes

should we integrate that `results.sarif` method?

**Comment by honeybhardwaj** [comment]
yes @Siddhant-K-code

**Comment by Siddhant-K-code** [comment]
Done!

**Review by honeybhardwaj — APPROVED** [review]
LGTM 👍🏻 well done @Siddhant-K-code

**Review by pranavbaburaj — APPROVED** [review]
Looks good 👍🏼

**Pull request merged**
